### ISSUE TITLE
Fix the broken CSS link for the site

### ISSUE THREAD

**Issue by sushant-j** [sushant-j/my-first-pull-request#120]
Right now, the file main.css from `assets` folder does not load correctly.

**Comment by matheusagcosta** [comment]
@sushant-j Please take a look on my PR above and let me know if that solves the problem.

**Comment by sushant-j** [comment]
Yes, it did solve the problem!
Thanks @matheusagcosta !

**Comment by matheusagcosta** [comment]
@sushant-j awesome! You're welcome!
