### ISSUE TITLE
1PR

### ISSUE THREAD

**Issue by parkerdyer** [sushant-j/my-first-pull-request#52]
I'd be happy to assist with improving this project once I've done my first PR. :) 

@sushant-j, I don't see the option to apply a label - is that a feature only available to the owner/admins? If so, the README will need to be updated.

**Comment by sushant-j** [comment]
@parkerdyer Yes, labels can only be applied by ones with write access to the repo. You can read more about them [here](https://help.github.com/articles/about-labels/). 
Also, all contributions are welcome! Looking forward to your PR!

P.S. You can retweet about the project in your circles for better reach :)
