### ISSUE TITLE
Completing the documentation

### ISSUE THREAD

**Issue by sushant-j** [sushant-j/my-first-pull-request#6]
I realised that the documentation could use some other contributors than me. I'd like if anyone would like to help complete next steps of documentation on README.md.

**Comment by gabrieluizramos** [comment]
I could improve the docs a little bit! I'll create the fork session :)

**Comment by gabrieluizramos** [comment]
I've submitted the #124 and #125

**Comment by sushant-j** [comment]
Thanks a lot for the helpful updates @gabrieluizramos! 
Happy HacktoberFest and Happy Hacking :)
